# lambda/serverless.yml
service: web-scraper

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2

functions:
  scraper:
    handler: src/handlers/scraper/index.handler
    events:
      - http:
          path: /scrape
          method: post
    timeout: 30